services:
  fex:
    build: .
    image: gladeowl/steam_fex_test
    container_name: steam_fex_test
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    # networks:
      # - proxy   # SHARED CADDY NETWORK
    stdin_open: true
    tty: true

# OPTIONAL SSL FOR EXTERNAL CADDY CONTAINER
# networks:
#   proxy:
#     external: true